# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AptOfflineQtCreateProfile.ui'
#
# Created: Mon Nov  8 17:23:31 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_CreateProfile(object):
    def setupUi(self, CreateProfile):
        CreateProfile.setObjectName("CreateProfile")
        CreateProfile.setWindowModality(QtCore.Qt.ApplicationModal)
        CreateProfile.resize(443, 374)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CreateProfile.sizePolicy().hasHeightForWidth())
        CreateProfile.setSizePolicy(sizePolicy)
        CreateProfile.setMinimumSize(QtCore.QSize(443, 374))
        CreateProfile.setMaximumSize(QtCore.QSize(443, 374))
        self.pushButton = QtGui.QPushButton(CreateProfile)
        self.pushButton.setGeometry(QtCore.QRect(334, 35, 98, 26))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/preferences-other.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.lblConsoleOutput = QtGui.QLabel(CreateProfile)
        self.lblConsoleOutput.setGeometry(QtCore.QRect(13, 183, 103, 17))
        self.lblConsoleOutput.setObjectName("lblConsoleOutput")
        self.packageList = QtGui.QLineEdit(CreateProfile)
        self.packageList.setEnabled(False)
        self.packageList.setGeometry(QtCore.QRect(146, 110, 171, 30))
        self.packageList.setMinimumSize(QtCore.QSize(0, 30))
        self.packageList.setReadOnly(False)
        self.packageList.setObjectName("packageList")
        self.lblPackageList = QtGui.QLabel(CreateProfile)
        self.lblPackageList.setGeometry(QtCore.QRect(16, 110, 128, 25))
        self.lblPackageList.setObjectName("lblPackageList")
        self.lblSaveProfile = QtGui.QLabel(CreateProfile)
        self.lblSaveProfile.setGeometry(QtCore.QRect(14, 153, 122, 17))
        self.lblSaveProfile.setObjectName("lblSaveProfile")
        self.installPackagesRadioBox = QtGui.QCheckBox(CreateProfile)
        self.installPackagesRadioBox.setGeometry(QtCore.QRect(122, 63, 127, 21))
        self.installPackagesRadioBox.setObjectName("installPackagesRadioBox")
        self.updateCheckBox = QtGui.QCheckBox(CreateProfile)
        self.updateCheckBox.setGeometry(QtCore.QRect(122, 13, 72, 21))
        self.updateCheckBox.setObjectName("updateCheckBox")
        self.profileFilePath = QtGui.QLineEdit(CreateProfile)
        self.profileFilePath.setEnabled(True)
        self.profileFilePath.setGeometry(QtCore.QRect(146, 148, 171, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileFilePath.sizePolicy().hasHeightForWidth())
        self.profileFilePath.setSizePolicy(sizePolicy)
        self.profileFilePath.setMinimumSize(QtCore.QSize(0, 30))
        self.profileFilePath.setObjectName("profileFilePath")
        self.browseFilePathButton = QtGui.QPushButton(CreateProfile)
        self.browseFilePathButton.setGeometry(QtCore.QRect(334, 148, 91, 30))
        self.browseFilePathButton.setMinimumSize(QtCore.QSize(91, 30))
        self.browseFilePathButton.setObjectName("browseFilePathButton")
        self.lblInstallType = QtGui.QLabel(CreateProfile)
        self.lblInstallType.setGeometry(QtCore.QRect(18, 38, 101, 17))
        self.lblInstallType.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblInstallType.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblInstallType.setObjectName("lblInstallType")
        self.upgradePackagesRadioBox = QtGui.QCheckBox(CreateProfile)
        self.upgradePackagesRadioBox.setGeometry(QtCore.QRect(122, 37, 142, 21))
        self.upgradePackagesRadioBox.setObjectName("upgradePackagesRadioBox")
        self.widget = QtGui.QWidget(CreateProfile)
        self.widget.setGeometry(QtCore.QRect(12, 204, 421, 151))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.consoleOutputHolder = QtGui.QTextEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleOutputHolder.sizePolicy().hasHeightForWidth())
        self.consoleOutputHolder.setSizePolicy(sizePolicy)
        self.consoleOutputHolder.setMinimumSize(QtCore.QSize(0, 100))
        self.consoleOutputHolder.setMaximumSize(QtCore.QSize(16777215, 100))
        self.consoleOutputHolder.setObjectName("consoleOutputHolder")
        self.verticalLayout.addWidget(self.consoleOutputHolder)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.createProfileButton = QtGui.QPushButton(self.widget)
        self.createProfileButton.setEnabled(True)
        self.createProfileButton.setMinimumSize(QtCore.QSize(100, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/dialog-ok-apply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createProfileButton.setIcon(icon1)
        self.createProfileButton.setObjectName("createProfileButton")
        self.horizontalLayout.addWidget(self.createProfileButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancelButton = QtGui.QPushButton(self.widget)
        self.cancelButton.setMinimumSize(QtCore.QSize(100, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/dialog-cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelButton.setIcon(icon2)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CreateProfile)
        QtCore.QMetaObject.connectSlotsByName(CreateProfile)

    def retranslateUi(self, CreateProfile):
        CreateProfile.setWindowTitle(QtGui.QApplication.translate("CreateProfile", "Generate Signature", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setToolTip(QtGui.QApplication.translate("CreateProfile", "Additional Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("CreateProfile", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.lblConsoleOutput.setText(QtGui.QApplication.translate("CreateProfile", "Console Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.packageList.setToolTip(QtGui.QApplication.translate("CreateProfile", "Install these packages separated by comma", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPackageList.setText(QtGui.QApplication.translate("CreateProfile", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Install these packages</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">separated by comma</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSaveProfile.setText(QtGui.QApplication.translate("CreateProfile", "Save Signature As ", None, QtGui.QApplication.UnicodeUTF8))
        self.installPackagesRadioBox.setToolTip(QtGui.QApplication.translate("CreateProfile", "Select to install specified packages", None, QtGui.QApplication.UnicodeUTF8))
        self.installPackagesRadioBox.setText(QtGui.QApplication.translate("CreateProfile", "Install Packages", None, QtGui.QApplication.UnicodeUTF8))
        self.updateCheckBox.setToolTip(QtGui.QApplication.translate("CreateProfile", "Select for APT\'s Database Update", None, QtGui.QApplication.UnicodeUTF8))
        self.updateCheckBox.setText(QtGui.QApplication.translate("CreateProfile", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.profileFilePath.setToolTip(QtGui.QApplication.translate("CreateProfile", "File to save signature as", None, QtGui.QApplication.UnicodeUTF8))
        self.browseFilePathButton.setText(QtGui.QApplication.translate("CreateProfile", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInstallType.setText(QtGui.QApplication.translate("CreateProfile", "Installation Type", None, QtGui.QApplication.UnicodeUTF8))
        self.upgradePackagesRadioBox.setToolTip(QtGui.QApplication.translate("CreateProfile", "Select for Packages that need to be upgraded", None, QtGui.QApplication.UnicodeUTF8))
        self.upgradePackagesRadioBox.setText(QtGui.QApplication.translate("CreateProfile", "Upgrade Packages", None, QtGui.QApplication.UnicodeUTF8))
        self.createProfileButton.setToolTip(QtGui.QApplication.translate("CreateProfile", "Press to Generate Signature", None, QtGui.QApplication.UnicodeUTF8))
        self.createProfileButton.setText(QtGui.QApplication.translate("CreateProfile", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setToolTip(QtGui.QApplication.translate("CreateProfile", "Press to Cancel operation", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("CreateProfile", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
